instructions about rTail, authomount folders, wiremock samples, WSO2 sample project, etc. added.

diff --git a/provision/wso2-stack-srv/puppet/modules/wiremock/files/wiremock b/provision/wso2-stack-srv/puppet/modules/wiremock/files/wiremock
--- a/provision/wso2-stack-srv/puppet/modules/wiremock/files/wiremock
+++ b/provision/wso2-stack-srv/puppet/modules/wiremock/files/wiremock
@@ -10,56 +10,55 @@
 # Description:       Deamon Service to Start up stopped services at server startup
 ### END INIT INFO
 
+PRODUCT_CODE="wiremock"
 USER="vagrant"
-PRODUCT_CODE="WIREMOCK"
-MOCK_HOME="/opt/wiremock"
 MOCK_SERVER_PORT="7788"
-LOCK_FILE="$MOCK_HOME/wiremock.lck"
-CMD_START="cd $MOCK_HOME ; java -jar wiremock-1.57-standalone.jar --port $MOCK_SERVER_PORT --verbose"
+LOCK_FILE="/opt/${PRODUCT_CODE}/wiremock.lck"
+MOCK_LOG_FILE="wiremock.log"
+CMD_START="cd /opt/${PRODUCT_CODE} ; java -jar wiremock-1.57-standalone.jar --port $MOCK_SERVER_PORT --verbose"
 CMD_STOP="kill -9"
 JAVA_HOME="/usr/java/latest"
-MOCK_LOG_FILE="wiremock.log"
 
 export JAVA_HOME=$JAVA_HOME
 
 # Status the service
 status() {
-   PID=`ps axww | grep 7788 | grep wiremock | grep -v grep | awk '{print $1}'`
-   ps -fp $PID > /dev/null 2>&1
-   PIDVAL=$?
-   if [ $PIDVAL -eq 0 ]
-      then
-         echo "$PRODUCT_CODE server is running ..."
-      else
-         echo "$PRODUCT_CODE server is stopped."
-   fi
-   return $PIDVAL
+  PID=`ps axww | grep 7788 | grep wiremock | grep -v grep | awk '{print $1}'`
+  ps -fp $PID > /dev/null 2>&1
+  PIDVAL=$?
+  if [ $PIDVAL -eq 0 ]
+    then
+      echo "[$PRODUCT_CODE] server is running (pid "$PID")"
+    else
+      echo "[$PRODUCT_CODE] server is stopped (pid not found)"
+  fi
+  return $PIDVAL
 }
 
 # Start the service
 start() {
-   PID=`ps axww | grep 7788 | grep wiremock | grep -v grep | awk '{print $1}'`
-   ps -fp $PID > /dev/null 2>&1
-   PIDVAL=$?
-   if [ $PIDVAL -eq 0 ]
-      then
-        echo "$PRODUCT_CODE server is running ..."
-      else
-        echo -n "Starting $PRODUCT_CODE server ... "
-        touch $LOCK_FILE
-        su - $USER -c "$CMD_START > $MOCK_LOG_FILE 2>&1 &"
-        sleep 5
-        PID=`ps axww | grep 7788 | grep wiremock | grep -v grep | awk '{print $1}'`
-        ps -fp $PID > /dev/null 2>&1
-        PIDVAL=$?
-        if [ $PIDVAL -eq 0 ]
-          then
-            echo "success"
-          else
-            echo "failure"
-        fi
-   fi
-   return $PIDVAL
+  PID=`ps axww | grep 7788 | grep wiremock | grep -v grep | awk '{print $1}'`
+  ps -fp $PID > /dev/null 2>&1
+  PIDVAL=$?
+  if [ $PIDVAL -eq 0 ]
+    then
+      echo "[$PRODUCT_CODE] server is running (pid "$PID")"
+    else
+      echo -n "[$PRODUCT_CODE] server starting ... "
+      touch $LOCK_FILE
+      su - $USER -c "$CMD_START > $MOCK_LOG_FILE 2>&1 &"
+      sleep 5
+      PID=`ps axww | grep 7788 | grep wiremock | grep -v grep | awk '{print $1}'`
+      ps -fp $PID > /dev/null 2>&1
+      PIDVAL=$?
+      if [ $PIDVAL -eq 0 ]
+        then
+          echo "success (pid "$PID")"
+        else
+          echo "failure (pid "$PID")"
+      fi
+  fi
+  return $PIDVAL
 }
 
 
@@ -70,7 +69,7 @@ stop() {
   PIDVAL=$?
   if [ $PIDVAL -eq 0 ]
       then
-         echo -n "Stopping $PRODUCT_CODE server ... "
+         echo -n "[$PRODUCT_CODE] server ... "
          su - $USER -c "$CMD_STOP $PID > /dev/null 2>&1 &"
          rm -f $LOCK_FILE
          sleep 10
@@ -79,14 +78,14 @@ stop() {
          PIDVAL=$?
          if [ $PIDVAL -eq 0 ]
              then
-                echo "failure"
+                echo "failure (pid "$PID")"
                 PIDVAL=2
              else
-                echo "success"
+                echo "success (pid "$PID")"
                 PIDVAL=0
          fi
       else
-         echo "$PRODUCT_CODE server is not running."
+         echo "[$PRODUCT_CODE] server is not running (pid not found)"
          PIDVAL=0
   fi
   return $PIDVAL
@@ -103,7 +102,7 @@ stop)
 status)
     status
     ;;
-restart|reload|condrestart)
+restart|reload)
     stop
     start
     ;;
diff --git a/provision/wso2-stack-srv/puppet/modules/wso2am/files/wso2am02a/wso2am02a b/provision/wso2-stack-srv/puppet/modules/wso2am/files/wso2am02a/wso2am02a
--- a/provision/wso2-stack-srv/puppet/modules/wso2am/files/wso2am02a/wso2am02a
+++ b/provision/wso2-stack-srv/puppet/modules/wso2am/files/wso2am02a/wso2am02a
@@ -6,151 +6,106 @@
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Service to Start up stopped services at server startup
-# Description:       Deamon Service to Start up stopped services at server startup
+# Short-Description: Service to start and stop server
+# Description:       Deamon service to start and stop server
 ### END INIT INFO
 
+PRODUCT_CODE="wso2am02a"
 USER="vagrant"
-PRODUCT_CODE="WSO2AM02A"
-CARBON_HOME="/opt/wso2am02a"
-LOCK_FILE="${CARBON_HOME}/wso2carbon.lck"
-PID_FILE="${CARBON_HOME}/wso2carbon.pid"
-CMD="${CARBON_HOME}/bin/wso2server.sh"
+PID_FILE="/opt/${PRODUCT_CODE}/wso2carbon.pid"
+CMD="/opt/${PRODUCT_CODE}/bin/wso2server.sh"
 JAVA_HOME="/usr/java/latest"
 
 export JAVA_HOME=$JAVA_HOME
 
-# Status the service
-status() {
- if [ -f $PID_FILE ]
-     then
-  PID=`cat $PID_FILE`
-  ps -fp $PID > /dev/null 2>&1
-  PIDVAL=$?
-     else
-  PIDVAL=3
- fi
-
- if [ $PIDVAL -eq 0 ]
-     then
-  echo "$PRODUCT_CODE server is running ..."
-     else
-  echo "$PRODUCT_CODE server is stopped."
- fi
- return $PIDVAL
-}
-
 # Start the service
-start() {
- if [ -f $PID_FILE ]
-  then
-    PID=`cat $PID_FILE`
-    ps -fp $PID > /dev/null 2>&1
-    PIDVAL=$?
-  else
-    PIDVAL=3
- fi
-
- if [ $PIDVAL -eq 0 ]
-   then
-      echo "$PRODUCT_CODE server is running ..."
-   else
-      echo -n "Starting $PRODUCT_CODE server ... "
-      touch $LOCK_FILE
-      su - $USER -c "$CMD start > /dev/null 2>&1 &"
-      sleep 5
-      if [ -f $PID_FILE ]
-        then
-          PID=`cat $PID_FILE`
-          ps -fp $PID > /dev/null 2>&1
-          PIDVAL=$?
-          if [ $PIDVAL -eq 0 ]
-            then
-              echo "success"
-            else
-              echo "failure"
-          fi
-        else
-          echo "failure"
-          PIDVAL=2
-      fi
- fi
- return $PIDVAL
-}
-
-# Restart the service
-restart() {
- echo -n "Restarting $PRODUCT_CODE server ... "
- touch $LOCK_FILE
- su - $USER -c "$CMD restart > /dev/null 2>&1 &"
- sleep 15
- if [ -f $PID_FILE ]
-     then
-  PID=`cat $PID_FILE`
-  ps -fp $PID > /dev/null 2>&1
-  PIDVAL=$?
-  if [ $PIDVAL -eq 0 ]
-      then
-   echo "success"
-      else
-   echo "failure"
+do_start() {
+  if [ -f $PID_FILE ]
+    then
+      PID=`cat $PID_FILE`
+      # Check if PID exists
+      ps -fp $PID > /dev/null 2>&1
+      VAL=$?
+    else
+      PID='null'
+      VAL=3
   fi
-     else
-  echo "failure"
-  PIDVAL=2
- fi
- echo
- return $PIDVAL
+
+  # VAL=0 -> PID exist
+  # VAL=1 -> PID not exist
+
+  if [ $VAL -eq 0 ]
+    then
+      echo "[$PRODUCT_CODE] server is already running (pid "$PID")"
+    else
+      echo -n "[$PRODUCT_CODE] starting server ... "
+      sleep 10
+      su - $USER -c $CMD start > /dev/null 2>&1 &
+      sleep 5
+      PID=`cat $PID_FILE`
+      if [ $PID -eq 0 ]
+        then
+          echo "failure (pid "$PID")"
+        else
+          echo "success (pid "$PID")"
+      fi
+  fi
 }
 
 # Stop the service
-stop() {
- if [ -f $PID_FILE ]
-     then
-  PID=`cat $PID_FILE`
-  ps -fp $PID > /dev/null 2>&1
-  PIDVAL=$?
-  if [ $PIDVAL -eq 0 ]
-      then
-   echo -n "Stopping $PRODUCT_CODE server ... "
-   su - $USER -c "$CMD stop > /dev/null 2>&1 &"
-   rm -f $LOCK_FILE
-   sleep 10
-   PID=`cat $PID_FILE`
-   ps -fp $PID > /dev/null 2>&1
-   PIDVAL=$?
-   if [ $PIDVAL -eq 0 ]
-       then
-    echo "failure"
-    PIDVAL=2
-       else
-    echo "success"
-    PIDVAL=0
-   fi
-      else
-         echo "$PRODUCT_CODE server is not running."
-         PIDVAL=0
+do_stop() {
+  if [ -f $PID_FILE ]
+    then
+      PID=`cat $PID_FILE`
+      echo -n "[$PRODUCT_CODE] stopping server ... "
+      su - $USER -c $CMD stop > /dev/null 2>&1 &
+      sleep 10
+      if [ $PID -eq 0 ]
+        then
+          echo "failure (pid "$PID")"
+        else
+          rm -f $PID_FILE
+          echo "success (pid "$PID")"
+      fi
+    else
+      echo "[$PRODUCT_CODE] server is already stopped (pid not found)."
   fi
-     else
-        echo "$PRODUCT_CODE server is not running."
-        PIDVAL=0
- fi
- return $PIDVAL
+}
+
+# Status the service
+do_status() {
+  if [ -f $PID_FILE ]
+    then
+      PID=`cat $PID_FILE`
+      ps -fp $PID > /dev/null 2>&1
+      PIDVAL=$?
+    else
+      PIDVAL=3
+  fi
+
+  if [ $PIDVAL -eq 0 ]
+    then
+      echo "[$PRODUCT_CODE] server is running (pid "$PID")"
+    else
+      echo "[$PRODUCT_CODE] server is stopped."
+  fi
+  return $PIDVAL
 }
 
 ### main logic ###
 case "$1" in
 start)
-    start
+    do_start
     ;;
 stop)
-    stop
+    do_stop
     ;;
 status)
-    status
+    do_status
     ;;
-restart|reload|condrestart)
-    restart
+restart|reload)
+    do_stop
+    do_start
     ;;
 *)
    echo $"Usage: $0 {start|stop|restart|reload|status}"
